spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: Rm552283
    password: 170204
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
